#!/usr/bin/env bash
# Regenerates data/contributions.yaml from the OpenDev Gerrit REST API.
#
# The register is a claim about being exhaustive, so it should not be kept
# in sync by hand. Run this, read the diff, commit it. The API is public and
# read-only: no credential is sent, and nothing about this machine is.
#
# Requires curl and jq.
set -euo pipefail

host="${GERRIT_HOST:-https://review.opendev.org}"
owner="${GERRIT_OWNER:-kallioli}"
out="${1:-data/contributions.yaml}"

for tool in curl jq; do
  command -v "$tool" >/dev/null || {
    echo "fetch-contributions: $tool is required" >&2
    exit 1
  }
done

# Gerrit prefixes every JSON response with an anti-XSSI line, ")]}'".
# Drop it only when it is actually there, so a change of API behaviour
# surfaces as a jq parse error rather than as a silently truncated file.
strip_xssi() {
  local first
  IFS= read -r first || return 0
  [[ "$first" == ")]}'" ]] || printf '%s\n' "$first"
  cat
}

query() {
  curl -fsS --get "$host/changes/" \
    --data-urlencode "q=$1" \
    --data-urlencode "n=250" |
    strip_xssi
}

# YAML scalars are emitted as JSON strings: always quoted, always escaped.
# A subject containing a colon is common and would otherwise be a mapping.
# shellcheck disable=SC2016  # $host below is a jq variable, bound with --arg.
to_yaml_rows='
  def rank: {"MERGED": 0, "NEW": 1, "ABANDONED": 2}[.status] // 3;
  group_by(rank)
  | map(sort_by(.created) | reverse)
  | flatten
  | map(
      "  - project: \(.project)\n"
      + "    number: \(._number)\n"
      + "    subject: \(.subject | tojson)\n"
      + "    status: \(.status)\n"
      + "    created: \(.created | split(" ")[0])\n"
      + "    url: \($host)/c/\(.project)/+/\(._number)"
    )
  | join("\n")
'

# shellcheck disable=SC2016  # $host below is a jq variable, bound with --arg.
to_yaml_reviews='
  sort_by(.project, ._number)
  | map(
      "  - project: \(.project)\n"
      + "    number: \(._number)\n"
      + "    subject: \(.subject | tojson)\n"
      + "    url: \($host)/c/\(.project)/+/\(._number)"
    )
  | join("\n")
'

authored=$(query "owner:$owner" | jq -r --arg host "$host" "$to_yaml_rows")
reviewed=$(query "reviewer:$owner -owner:$owner" | jq -r --arg host "$host" "$to_yaml_reviews")

[[ -n "$authored" ]] || {
  echo "fetch-contributions: the owner query returned nothing, refusing to write an empty register" >&2
  exit 1
}

tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

cat >"$tmp" <<EOF
# OpenStack upstream contributions - Kevin Allioli
# Gerrit account: $owner
# Source: ${host#https://} REST API, fetched $(date -u +%Y-%m-%d)
#
# Generated by scripts/fetch-contributions.sh. Do not edit by hand: rerun the
# script instead. Rendered by layouts/contributions/section.html, which fails
# the build if a status it does not know about would drop a row.

profile: $host/q/owner:$owner

authored:
$authored

reviewed:
$reviewed
EOF

mv "$tmp" "$out"
trap - EXIT
echo "fetch-contributions: wrote $out"
